# Generated by Django 3.0.8 on 2020-07-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200722_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quesiton_description',
            field=models.CharField(default='No description', max_length=200),
        ),
    ]
