# Generated by Django 3.0.8 on 2020-07-22 17:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200722_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 17, 38, 22, 844138, tzinfo=utc), verbose_name='date published'),
        ),
    ]
