# Generated by Django 3.0.8 on 2020-07-26 15:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_voters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='voters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default='list', size=None),
        ),
    ]
