# Generated by Django 3.0.8 on 2020-07-22 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200722_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quesiton_description',
            new_name='description',
        ),
    ]
