# Generated by Django 3.0.8 on 2020-07-28 12:37

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polluser',
            name='nots',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=[], size=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_text', models.CharField(max_length=200)),
                ('not_from', models.CharField(max_length=100)),
                ('readStatus', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.PollUser')),
            ],
        ),
    ]
