# Generated by Django 3.0.8 on 2020-07-28 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200728_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polluser',
            name='nots',
        ),
    ]
