# Generated by Django 3.0.8 on 2020-07-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notify_typeperm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='readStatus',
            field=models.BooleanField(default=False),
        ),
    ]
